"""'Lat_and_long_to_Shop_table'

Revision ID: 2303e70aaafa
Revises: d2796fedb05d
Create Date: 2021-01-25 19:36:13.269877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2303e70aaafa'
down_revision = 'd2796fedb05d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('SYS_CONSTRAINT_52f3dab5-9d84-45cf-a3cb-b4ca7624909d', 'receipt', type_='foreignkey')
    op.drop_constraint('SYS_CONSTRAINT_c7e231a2-bf00-4c49-b2d6-3530d430c1a2', 'receipt', type_='foreignkey')
    op.create_foreign_key(None, 'receipt', 'product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'receipt', 'shop', ['shop_id'], ['id'])
    op.add_column('shop', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('shop', sa.Column('long', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'long')
    op.drop_column('shop', 'lat')
    op.drop_constraint(None, 'receipt', type_='foreignkey')
    op.drop_constraint(None, 'receipt', type_='foreignkey')
    op.create_foreign_key('SYS_CONSTRAINT_c7e231a2-bf00-4c49-b2d6-3530d430c1a2', 'receipt', 'product', ['product_id'], ['id'], referent_schema='develop')
    op.create_foreign_key('SYS_CONSTRAINT_52f3dab5-9d84-45cf-a3cb-b4ca7624909d', 'receipt', 'shop', ['shop_id'], ['id'], referent_schema='develop')
    # ### end Alembic commands ###
