"""Deleted vat from receipts in model

Revision ID: 32192ddebc1e
Revises: ce57b0e18b07
Create Date: 2021-02-03 18:41:31.037121

"""
from alembic import op
import sqlalchemy as sa
import snowflake

# revision identifiers, used by Alembic.
revision = '32192ddebc1e'
down_revision = 'ce57b0e18b07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'id',
               existing_type=sa.DECIMAL(precision=38, scale=0),
               type_=sa.Integer(),
               autoincrement=True)
    op.alter_column('product', 'qty',
               existing_type=sa.DECIMAL(precision=38, scale=0),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('receipt', 'datetime',
               existing_type=snowflake.sqlalchemy.custom_types.TIMESTAMP_NTZ(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('receipt', 'id',
               existing_type=sa.DECIMAL(precision=38, scale=0),
               type_=sa.Integer(),
               autoincrement=True)
    op.alter_column('receipt', 'product_id',
               existing_type=sa.DECIMAL(precision=38, scale=0),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('receipt', 'shop_id',
               existing_type=sa.DECIMAL(precision=38, scale=0),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint('SYS_CONSTRAINT_4886959e-a585-4a53-9105-5a79f7fd8fda', 'receipt', type_='foreignkey')
    op.drop_constraint('SYS_CONSTRAINT_e8634a38-d574-48ee-becd-76badcc82721', 'receipt', type_='foreignkey')
    op.create_foreign_key(None, 'receipt', 'product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'receipt', 'shop', ['shop_id'], ['id'])
    op.drop_column('receipt', 'vat')
    op.alter_column('shop', 'id',
               existing_type=sa.DECIMAL(precision=38, scale=0),
               type_=sa.Integer(),
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop', 'id',
               existing_type=sa.Integer(),
               type_=sa.DECIMAL(precision=38, scale=0),
               autoincrement=True)
    op.add_column('receipt', sa.Column('vat', sa.FLOAT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'receipt', type_='foreignkey')
    op.drop_constraint(None, 'receipt', type_='foreignkey')
    op.create_foreign_key('SYS_CONSTRAINT_e8634a38-d574-48ee-becd-76badcc82721', 'receipt', 'product', ['product_id'], ['id'], referent_schema='develop')
    op.create_foreign_key('SYS_CONSTRAINT_4886959e-a585-4a53-9105-5a79f7fd8fda', 'receipt', 'shop', ['shop_id'], ['id'], referent_schema='develop')
    op.alter_column('receipt', 'shop_id',
               existing_type=sa.Integer(),
               type_=sa.DECIMAL(precision=38, scale=0),
               existing_nullable=False)
    op.alter_column('receipt', 'product_id',
               existing_type=sa.Integer(),
               type_=sa.DECIMAL(precision=38, scale=0),
               existing_nullable=False)
    op.alter_column('receipt', 'id',
               existing_type=sa.Integer(),
               type_=sa.DECIMAL(precision=38, scale=0),
               autoincrement=True)
    op.alter_column('receipt', 'datetime',
               existing_type=sa.DateTime(),
               type_=snowflake.sqlalchemy.custom_types.TIMESTAMP_NTZ(),
               existing_nullable=False)
    op.alter_column('product', 'qty',
               existing_type=sa.Integer(),
               type_=sa.DECIMAL(precision=38, scale=0),
               existing_nullable=True)
    op.alter_column('product', 'id',
               existing_type=sa.Integer(),
               type_=sa.DECIMAL(precision=38, scale=0),
               autoincrement=True)
    # ### end Alembic commands ###
