"""Added autoincrement to product table

Revision ID: 6087d7482ff5
Revises: 2303e70aaafa
Create Date: 2021-01-27 18:21:43.850853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6087d7482ff5'
down_revision = '2303e70aaafa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('SYS_CONSTRAINT_d3420eb5-a4e9-4472-a1a4-d92a1900e261', 'receipt', type_='foreignkey')
    op.drop_constraint('SYS_CONSTRAINT_75c33fd6-7028-466d-8f66-d5c3b71a3a3e', 'receipt', type_='foreignkey')
    op.create_foreign_key(None, 'receipt', 'shop', ['shop_id'], ['id'])
    op.create_foreign_key(None, 'receipt', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receipt', type_='foreignkey')
    op.drop_constraint(None, 'receipt', type_='foreignkey')
    op.create_foreign_key('SYS_CONSTRAINT_75c33fd6-7028-466d-8f66-d5c3b71a3a3e', 'receipt', 'product', ['product_id'], ['id'], referent_schema='develop')
    op.create_foreign_key('SYS_CONSTRAINT_d3420eb5-a4e9-4472-a1a4-d92a1900e261', 'receipt', 'shop', ['shop_id'], ['id'], referent_schema='develop')
    # ### end Alembic commands ###
