"""Added autoincrement to shop table

Revision ID: b597dd08aa7d
Revises: 6087d7482ff5
Create Date: 2021-01-27 18:23:37.850065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b597dd08aa7d'
down_revision = '6087d7482ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('SYS_CONSTRAINT_2ab1affc-6156-4893-b4f4-33065b5052e8', 'receipt', type_='foreignkey')
    op.drop_constraint('SYS_CONSTRAINT_d4755a0c-7594-450e-bc81-6814ee656ad6', 'receipt', type_='foreignkey')
    op.create_foreign_key(None, 'receipt', 'product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'receipt', 'shop', ['shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receipt', type_='foreignkey')
    op.drop_constraint(None, 'receipt', type_='foreignkey')
    op.create_foreign_key('SYS_CONSTRAINT_d4755a0c-7594-450e-bc81-6814ee656ad6', 'receipt', 'shop', ['shop_id'], ['id'], referent_schema='develop')
    op.create_foreign_key('SYS_CONSTRAINT_2ab1affc-6156-4893-b4f4-33065b5052e8', 'receipt', 'product', ['product_id'], ['id'], referent_schema='develop')
    # ### end Alembic commands ###
