"""Changes in shop.id column

Revision ID: bd233b96ea0d
Revises: b597dd08aa7d
Create Date: 2021-01-27 18:36:21.786081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd233b96ea0d'
down_revision = 'b597dd08aa7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('SYS_CONSTRAINT_901e21a9-259b-4df4-89c3-99161daade6f', 'receipt', type_='foreignkey')
    op.drop_constraint('SYS_CONSTRAINT_4af33d7c-32a3-4090-bcb4-fb68e717267d', 'receipt', type_='foreignkey')
    op.create_foreign_key(None, 'receipt', 'shop', ['shop_id'], ['id'])
    op.create_foreign_key(None, 'receipt', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receipt', type_='foreignkey')
    op.drop_constraint(None, 'receipt', type_='foreignkey')
    op.create_foreign_key('SYS_CONSTRAINT_4af33d7c-32a3-4090-bcb4-fb68e717267d', 'receipt', 'shop', ['shop_id'], ['id'], referent_schema='develop')
    op.create_foreign_key('SYS_CONSTRAINT_901e21a9-259b-4df4-89c3-99161daade6f', 'receipt', 'product', ['product_id'], ['id'], referent_schema='develop')
    # ### end Alembic commands ###
