"""Added sequences to Product and Shop

Revision ID: ce57b0e18b07
Revises: 441ae047adaf
Create Date: 2021-01-28 19:07:31.997242

"""
from alembic import op
import sqlalchemy as sa
import snowflake


# revision identifiers, used by Alembic.
revision = 'ce57b0e18b07'
down_revision = '441ae047adaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'id',
               existing_type=sa.DECIMAL(precision=38, scale=0),
               type_=sa.Integer(),
               autoincrement=True)
    op.alter_column('product', 'qty',
               existing_type=sa.DECIMAL(precision=38, scale=0),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('receipt', 'datetime',
               existing_type=snowflake.sqlalchemy.custom_types.TIMESTAMP_NTZ(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('receipt', 'id',
               existing_type=sa.DECIMAL(precision=38, scale=0),
               type_=sa.Integer(),
               autoincrement=True)
    op.alter_column('receipt', 'product_id',
               existing_type=sa.DECIMAL(precision=38, scale=0),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('receipt', 'shop_id',
               existing_type=sa.DECIMAL(precision=38, scale=0),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint('SYS_CONSTRAINT_4c598903-ab26-4a41-b4ac-6563135139b0', 'receipt', type_='foreignkey')
    op.drop_constraint('SYS_CONSTRAINT_c8df85cc-84ad-4add-9aae-98453d30f5af', 'receipt', type_='foreignkey')
    op.create_foreign_key(None, 'receipt', 'shop', ['shop_id'], ['id'])
    op.create_foreign_key(None, 'receipt', 'product', ['product_id'], ['id'])
    op.alter_column('shop', 'id',
               existing_type=sa.DECIMAL(precision=38, scale=0),
               type_=sa.Integer(),
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop', 'id',
               existing_type=sa.Integer(),
               type_=sa.DECIMAL(precision=38, scale=0),
               autoincrement=True)
    op.drop_constraint(None, 'receipt', type_='foreignkey')
    op.drop_constraint(None, 'receipt', type_='foreignkey')
    op.create_foreign_key('SYS_CONSTRAINT_c8df85cc-84ad-4add-9aae-98453d30f5af', 'receipt', 'shop', ['shop_id'], ['id'], referent_schema='develop')
    op.create_foreign_key('SYS_CONSTRAINT_4c598903-ab26-4a41-b4ac-6563135139b0', 'receipt', 'product', ['product_id'], ['id'], referent_schema='develop')
    op.alter_column('receipt', 'shop_id',
               existing_type=sa.Integer(),
               type_=sa.DECIMAL(precision=38, scale=0),
               existing_nullable=False)
    op.alter_column('receipt', 'product_id',
               existing_type=sa.Integer(),
               type_=sa.DECIMAL(precision=38, scale=0),
               existing_nullable=False)
    op.alter_column('receipt', 'id',
               existing_type=sa.Integer(),
               type_=sa.DECIMAL(precision=38, scale=0),
               autoincrement=True)
    op.alter_column('receipt', 'datetime',
               existing_type=sa.DateTime(),
               type_=snowflake.sqlalchemy.custom_types.TIMESTAMP_NTZ(),
               existing_nullable=False)
    op.alter_column('product', 'qty',
               existing_type=sa.Integer(),
               type_=sa.DECIMAL(precision=38, scale=0),
               existing_nullable=True)
    op.alter_column('product', 'id',
               existing_type=sa.Integer(),
               type_=sa.DECIMAL(precision=38, scale=0),
               autoincrement=True)
    # ### end Alembic commands ###
